title "Runtime records"
Actor User
Actor Admin
participant "Front end" as FE
participant "Back end" as BE
database "Database" as DB

activate User
activate Admin
activate FE
activate BE
activate DB

==Transaction: Show Item==
FE -> BE: GetItems()
BE -> DB: GetItems()
DB --> BE: Items
BE --> FE: Items
User -> FE: Click on Item
FE -> BE: GetItem(ItemId)
BE --> FE: Item
FE -> FE: ShowItem(Item)
==Transaction: Add items to shopping cart==
FE -> BE: GetItems()
BE -> DB: GetItems()
DB --> BE: Items
BE --> FE: Items
User -> FE: Click on Item
FE -> FE: ShowItem(Item)
activate FE
FE -> BE: GetItem(ItemId)
BE --> FE: Item
deactivate FE
User -> FE: Click on add Item to shopping cart
FE -> BE: Add Item to shopping cart
BE -> BE: SetReserved()
FE -> BE: GetShoppingCartCount()
FE -> FE: ShowShoppingCartCount()
==Transaction: View shopping cart==
User -> FE: Click on shopping cart
FE -> BE: GetPage(shoppingCart)
FE -> BE: GetShoppingCartItems()
FE -> FE: ShowShoppingCartItems()
==Transaction: Delete item from shopping cart==
note left FE: User has to be on shopping cart page
User -> FE: Click on remove item
FE -> BE: RemoveItem(ItemId)
==Transaction: Register==
User -> FE: Click register button
loop While form has errors
    FE -> BE: GetForm(Register)
    FE -> FE: ShowForm(FormResults)
    User -> FE: Fill in form
    User -> FE: Send form
    FE -> BE: Post form
    BE -> BE: ValidateForm
end
BE -> DB: CreateUser(user)
BE -> FE: ShowPage(Home)
==Transaction: Login==
loop While form has errors
User -> FE: Fill in login form
User -> FE: Send login form
FE -> BE: Post form
BE -> BE: ValidateForm
activate BE
BE -> DB: GetUser(UserId)
DB --> BE: User
deactivate BE
end
BE -> BE: SetSessionUser
BE -> FE: ShowPage(Home)

==Transaction: View Profile==
note left FE: User has to be logged in
User -> FE: Press "view profile" button
FE -> BE: GetProfile()
BE -> DB: GetProfile(UserId)
DB --> BE: Profile
BE --> FE: Profile

==Transaction: Edit search criteria==
note left FE: User has to be on profile page
User -> FE: Press "edit search criteria" button
FE -> BE: GetSearchCriteria()
BE --> FE: SeachCriteria
FE -> FE: ShowSearchCriteriaPage
User -> FE: Edit search criteria
FE -> BE: UpdateSearchCriteria(newCriteria)
BE -> DB: UpdateSearchCriteria(newCriteria)

==Transaction: View purchase history==
note left FE: User has to be on profile page
User -> FE: Press "Purchase history" button
FE -> BE: GetPurchaseHistory()
BE -> DB: GetPurchaseHistory(UserId)
DB --> BE: PurchaseHistory
BE --> FE: PurchaseHistory
FE -> FE: ShowPurchaseHistory()

==Transaction: AddItem==
Admin -> FE: Press "Add Item" button
FE -> FE: show Add Item form
Admin -> FE: Fill in Add item form
FE -> BE: AddItem(Item)
BE -> DB: AddItem(Item)
==Transaction: EditItem==
Admin -> FE: Click on Item
FE -> BE: GetItem(ItemId)
BE -> DB: GetItem(ItemId)
DB --> BE: Item
BE --> FE: Item
FE -> FE: ShowItem(Item)
Admin -> FE: Click on Edit item
FE -> FE: ShowEditScreen()
Admin -> FE: Edit item
FE -> BE: UpdateItem(Item)
BE -> DB: UpdateItem(Item)

deactivate User
deactivate Admin
deactivate FE
deactivate BE
deactivate DB